### ISSUE TITLE
Stream file from S3

### ISSUE THREAD

**Issue by veilig2000** [thephpleague/flysystem-aws-s3-v2#3] opened 2015-01-29 15:58 UTC
I'm trying the same thing in a laravel app as this original issue thephpleague/flysystem#273 - downloading a file, ranging from 10M - 1G+, from S3. It appeared my app had to fully download the file from S3 before it would stream to the client, not seamlessly stream the file.

Is this still not possible?  

Or is there a better way I should be handling this?

``` PHP
$s3Client = S3Client::factory([
    'key' => '<key>',
    'secret' => '<secret>',
]);
// Not sure if this is actually needed w/ Flysystem?
$s3Client->registerStreamWrapper();                                                    

$filesystem = new Filesystem(
    new AwsS3Adapter($s3Client, '<bucket>')
);

return \Response::stream(function() use ($filesystem, $file) {
    fpassthru($filesystem->readStream($file));
}, 200, $headers);
```

As a side note - if I utilize the ~~recommended~~ offered approach from AWS to download, it appears to work correctly. http://docs.aws.amazon.com/aws-sdk-php/guide/latest/feature-s3-stream-wrapper.html#downloading-data

``` PHP
$stream = fopen($file, 'r')
return \Response::stream(function() use ($stream) {              
    while (!feof($stream)) {                                     
        echo fread($stream, 1024);                               
    }                                                            
    fclose($stream);                                             
}, 200, $headers); 
```

**Comment by frankdejonge** [comment] 2015-02-01 18:16
@veilig2000 Hi, either of the two implementation above should work just fine without loading everything into mem at once. The other issue was about the Sftp adapter, not the S3 one, which until recently didn't support streams as input. This has recently been resolved too btw. Looking at the `fpassthru` docs it seems the second implementation is indeed preferred for big files as `fpassthru` can consume massive amounts of mem.

**Comment by frankdejonge** [comment] 2015-02-01 18:18
@veilig2000 also, the registerStreamWrapper is not needed for Flysystem. Since the memory issue is not caused by Flysystem but by PHP itself, I'm closing this issue.

**Closed as completed by frankdejonge** 2015-02-01 18:18 UTC
